[package]
name = "counters-stub"
version = "0.0.1"
edition = "2021"

[package.metadata.component]
package = "rpc:counters"

[package.metadata.component.target]
world = "wasm-rpc-stub-counters"
path = "wit"

[package.metadata.component.target.dependencies."golem:rpc"]
path = "wit/deps/wasm-rpc"

[package.metadata.component.target.dependencies."rpc:counters"]
path = "wit/deps/rpc_counters"

[dependencies.golem-wasm-rpc]
version = "0.0.29"
features = ["stub"]
default-features = false

[dependencies.wit-bindgen-rt]
version = "0.26.0"
features = ["bitflags"]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
required-features = []

[profile.release]
opt-level = "s"
lto = true
strip = true
