[config]
default_to_workspace = false

[tasks.add-stub-dependency-rust-component-service-rust-rpc-service]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "rust-component-service-stub/wit", "--dest-wit-root", "rust-rpc-service/wit", "--overwrite", "--update-cargo-toml"]
command = "golem-cli"
cwd = "."
dependencies = ["generate-rust-component-service-stub"]

[tasks.build]
args = ["build"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.build-flow]
dependencies = ["build", "post-build"]

[tasks.build-release]
args = ["build", "--release"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.clean]
args = ["clean"]
command = "cargo-component"

[tasks.compose-release-rust-rpc-service]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/release/rust_rpc_service.wasm", "--stub-wasm", "target/wasm32-wasi/release/rust_component_service_stub.wasm", "--dest-wasm", "target/wasm32-wasi/release/rust_rpc_service_composed.wasm"]
command = "golem-cli"
cwd = "."

[tasks.compose-rust-rpc-service]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/debug/rust_rpc_service.wasm", "--stub-wasm", "target/wasm32-wasi/debug/rust_component_service_stub.wasm", "--dest-wasm", "target/wasm32-wasi/debug/rust_rpc_service_composed.wasm"]
command = "golem-cli"
cwd = "."

[tasks.default]
alias = "build"

[tasks.generate-rust-component-service-stub]
args = ["stubgen", "generate", "-s", "rust-component-service/wit", "-d", "rust-component-service-stub"]
command = "golem-cli"
cwd = "."

[tasks.post-build]
dependencies = ["compose-rust-rpc-service"]

[tasks.post-build-release]
dependencies = ["compose-release-rust-rpc-service"]

[tasks.regenerate-stubs]
dependencies = ["add-stub-dependency-rust-component-service-rust-rpc-service"]

[tasks.release-build-flow]
dependencies = ["build-release", "post-build-release"]

[tasks.test]
args = ["test"]
command = "cargo-component"
dependencies = ["clean"]
