version: '3.7'

services:
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - 6379:${REDIS_PORT-6379}

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: golem_db
      POSTGRES_USER: golem_user
      POSTGRES_PASSWORD: golem_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:${POSTGRES_PORT-5432}

  golem-shard-manager:
    image: golemservices/golem-shard-manager:latest
    pull_policy: always
    environment:
      - REDIS_HOST=redis
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - RUST_LOG=info,h2=warn,hyper=warn,tower=warn
      - GOLEM__REDIS__HOST=redis
      - GOLEM__REDIS__PORT=6379
      - GOLEM__HTTP_PORT=${SHARD_MANAGER_HTTP_PORT:-8081}
      - GOLEM_SHARD_MANAGER_PORT=${SHARD_MANAGER_GRPC_PORT:-9002}
    depends_on:
      - redis

  golem-service:
    image: golemservices/golem-service:latest
    pull_policy: always
    restart: on-failure
    environment:
      - ENVIRONMENT=local
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - RUST_LOG=info,h2=warn,hyper=warn,tower=warn
      - GOLEM__TEMPLATES__STORE__TYPE="Local"
      - GOLEM__TEMPLATES__STORE__CONFIG__OBJECT_PREFIX=""
      - GOLEM__TEMPLATES__STORE__CONFIG__ROOT_PATH=/template_store
      - GOLEM__DB__TYPE=Postgres
      - GOLEM__DB__CONFIG__DATABASE=golem_db
      - GOLEM__DB__CONFIG__MAX_CONNECTIONS=10
      - GOLEM__DB__CONFIG__HOST=postgres
      - GOLEM__DB__CONFIG__USERNAME=golem_user
      - GOLEM__DB__CONFIG__PASSWORD=golem_password
      - GOLEM__ROUTING_TABLE__HOST="golem-shard-manager"
      - GOLEM__ROUTING_TABLE__PORT=${SHARD_MANAGER_GRPC_PORT:-9002}
      - GOLEM__GRPC_PORT=${GOLEM_SERVICE_GRPC_PORT:-9090}
      - GOLEM__HTTP_PORT=${GOLEM_SERVICE_HTTP_PORT:-9881}
    volumes:
      - template_store:/template_store
    ports:
      - "${GOLEM_SERVICE_HTTP_PORT:-9881}:${GOLEM_SERVICE_HTTP_PORT:-9881}"
      - "${GOLEM_SERVICE_GRPC_PORT:-9090}:${GOLEM_SERVICE_GRPC_PORT:-9090}"
    depends_on:
      - postgres

  golem-worker-executor:
    image: golemservices/golem-worker-executor:latest
    pull_policy: always
    environment:
      - ENVIRONMENT=local
      - RUST_LOG=info
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - GOLEM__REDIS__PORT=6379
      - GOLEM__REDIS__HOST=redis
      - GOLEM__TEMPLATE_SERVICE__CONFIG__HOST=golem-service
      - GOLEM__TEMPLATE_SERVICE__CONFIG__PORT=${GOLEM_SERVICE_GRPC_PORT:-9090}
      - GOLEM__TEMPLATE_SERVICE__CONFIG__ACCESS_TOKEN="2A354594-7A63-4091-A46B-CC58D379F677"
      - GOLEM__PORT=${WORKER_EXECUTOR_GRPC_PORT:-9000}
      - GOLEM__HTTP_PORT=${WORKER_EXECUTOR_HTTP_PORT:-8082}
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__HOST=golem-shard-manager
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__PORT=${SHARD_MANAGER_GRPC_PORT:-9002}
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_ATTEMPTS=5
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MIN_DELAY="100ms"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_DELAY="2s"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MULTIPLIER=2
      - GOLEM__BLOB_STORE_SERVICE__CONFIG__REGION=us-east-1
      - GOLEM__COMPILED_TEMPLATE_SERVICE__CONFIG__ROOT="data/templates"
      - GOLEM__COMPILED_TEMPLATE_SERVICE__TYPE="Local"
      - GOLEM__SHARD_MANAGER_SERVICE__TYPE="Grpc"
    ports:
      - "${WORKER_EXECUTOR_HTTP_PORT:-8082}:${WORKER_EXECUTOR_HTTP_PORT:-8082}"

volumes:
  redis_data:
    driver: local
  template_store:
    driver: local
  postgres_data:
    driver: local